### ISSUE TITLE
1.14.4 Crashing

### ISSUE THREAD

**Issue by Wissi** [JibayMcs/Ama-s-Damage-Indicator#2]
Awesome work, thank you very much.

We have been using it and working nice.
As we updated, the client is crashing sporadically.
Full crash log [here](https://gist.github.com/Talyda/cc4374025e911a695a23b1b7fbf9462b).

Using:
forge-1.14.4-28.1.69.jar
damage_indicator-0.0.7.jar

Hope it's and easy/fast fix.
Will re-add to our modpack when you update.
Thanks again.

**Comment by noobanidus** [comment]
I noticed this error in a log that someone reported for Druidcraft. By the look of it, it's attempting to send something from the client as though it was on the server, and is getting a null pointer when it's trying to find the server; possibly you're just missing a side/isRemote check.

`at fr.zeamateis.damage_indicator.amy.network.AmyNetwork.sendPacketToEveryone(AmyNetwork.java:31) ~[?:0.0.7] {re:classloading}`

This line is very concerning. I would strongly recommend only sending the message to people who a re tracking the entity in question, rather than to everyone on the server; especially given that this is happening (potentially) in every LivingHeal event, you are likely going to spam people (even in other dimensions) with unnecessary packets and network overhead.

Where this was previously an easy thing, you'll now have to do something more complex: with your SimpleChannel `HANDLER` (for example), you'd want to do `HANDLER.send(PacketDistributor.TRACKING_ENTITY.with(() -> entityHere), message)`. 

The PacketDistributor has almost all of the previously used functions, including the ones that already have an easy method (sending to player, etc).

**Comment by JibayMcs** [comment]
Fixed in last commit.
Thanks a lot @noobanidus ;)
https://github.com/JibayMcs/Ama-s-Damage-Indicator/commit/f4d1c5ca9521f7bd61a904b098d3196a7abb1563

**Comment by noobanidus** [comment]
Glad to be of help!
